"""Totality: what the package produces, the package must consume.

Every other test in this suite measures a function against inputs chosen
for it. This one measures the surface against inputs the *package itself*
produces, which is the question none of the others ask.

It exists because a defect once crossed eight formal properties, a ported
reference suite of 109 cases, an enumeration of the last column of all
thousand rows, full statement and branch coverage and four linters. All
of those measured the serialization format from inside, with inputs the
codec knew how to generate. None asked what the rest of the package emits
that the codec has to accept, and the answer was that ``compose`` emitted
a multi-quadrant index the codec refused.

Three things keep this from decaying into the hand-written list it exists
to replace. The census of the public surface is mechanical, and the
completeness of that census is itself an assertion, so a name added later
must land in a bucket or in a named exemption rather than slipping past.
The exemption for unimplemented stubs asserts that they still raise
:class:`NotImplementedError`, so it turns red on the day one of them is
implemented instead of quietly excusing a working function. And the
corpus is enumerated rather than sampled, with the size of every entry
declared, because a green table with no counts hides an empty bucket.
"""

from __future__ import annotations

import inspect
from typing import Any, Callable, Iterator

import pytest
from shapely.geometry import Polygon

import itacart
from itacart.exceptions import ITACaRTError

EMPTY = inspect.Parameter.empty

# --------------------------------------------------------------------------
# Mechanical census of the public surface
# --------------------------------------------------------------------------

#: First-parameter names that mean "an index or a cell arrives here".
_INDEX_PARAMETERS = frozenset({"index", "cell", "cells", "origin"})

#: Producers of indices and regions. The corpus comes from these, and none
#: of them may also stand in for the surface being measured: a corpus
#: generated by the consumer under test measures nothing.
PRODUCER_NAMES = (
    "compose",
    "normalize",
    "compact_cells",
    "polyfill",
    "get_children",
    "uncompact_cells",
    "geo_to_cell",
    "vertex_to_cell",
)

#: Names exempt because they are not implemented yet. The exemption is an
#: assertion, not a licence: see the test that keeps it honest.
UNIMPLEMENTED_STUBS = (
    "ITACaRT",
    "cell_to_wkt",
    "cells_to_geojson",
    "cells_to_wkt",
    "conformance",
    "crs",
    "describe",
    "from_geodataframe",
    "to_geodataframe",
)

#: Second and later arguments for the consumers that require them. The
#: table's completeness is asserted, so a consumer that grows a required
#: argument fails here rather than being skipped.
EXTRA_ARGUMENTS: dict[str, tuple[Any, ...]] = {
    "are_neighbor_cells": ("NE(0001/0000)",),
    "cells_to_directed_edge": ("NE(0001/0000)",),
    "deflect": ("E",),
    "get_descendants": (2,),
    "get_neighbor": ("E",),
    "grid_distance": ("NE(0001/0000)",),
    "uncompact_cells": (2,),
}


def _public_callables() -> Iterator[tuple[str, Callable[..., Any]]]:
    for name in sorted(itacart.__all__):
        value = getattr(itacart, name)
        if callable(value):
            yield name, value


def _first_parameter(function: Callable[..., Any]) -> str | None:
    try:
        parameters = list(inspect.signature(function).parameters.values())
    except (TypeError, ValueError):
        return None
    return parameters[0].name if parameters else None


def _required_extras(function: Callable[..., Any]) -> list[str]:
    try:
        parameters = list(inspect.signature(function).parameters.values())
    except (TypeError, ValueError):
        return []
    return [
        parameter.name
        for parameter in parameters[1:]
        if parameter.default is EMPTY
        and parameter.kind
        in (parameter.POSITIONAL_ONLY, parameter.POSITIONAL_OR_KEYWORD)
    ]


def _classify(name: str) -> set[str]:
    """Tag a public name. Every name must earn at least one tag."""
    tags: set[str] = set()
    if name in UNIMPLEMENTED_STUBS:
        tags.add("stub")
    value = getattr(itacart, name)
    if isinstance(value, type):
        tags.add("type")
    if name in PRODUCER_NAMES:
        tags.add("producer")
    if callable(value) and not isinstance(value, type):
        first = _first_parameter(value)
        if first in _INDEX_PARAMETERS:
            tags.add("consumer")
        elif first is not None:
            tags.add("other-signature")
        else:
            tags.add("no-arguments")
    if not callable(value):
        tags.add("constant")
    return tags


def _consumers() -> list[str]:
    return [
        name
        for name, _ in _public_callables()
        if "consumer" in _classify(name) and "stub" not in _classify(name)
    ]


def test_the_census_classifies_every_public_name() -> None:
    """No name escapes the census in silence.

    This is the assertion that keeps the instrument from ageing into the
    hand-written list it replaces. A name added to the package must land
    in a bucket or in a named exemption; there is no third outcome.
    """
    unclassified = [name for name in itacart.__all__ if not _classify(name)]
    assert unclassified == [], f"unclassified public names: {unclassified}"


def test_the_census_reaches_the_whole_surface() -> None:
    """The buckets partition the surface, and the counts are declared."""
    tally: dict[str, int] = {}
    for name in itacart.__all__:
        for tag in _classify(name):
            tally[tag] = tally.get(tag, 0) + 1
    assert len(itacart.__all__) == 143, "surface changed; update the counts below"
    assert tally["stub"] == 9
    assert tally["consumer"] >= 50
    assert tally["producer"] == len(PRODUCER_NAMES)


def test_the_stub_exemption_expires_by_itself() -> None:
    """Exempt names must still be unimplemented.

    An exemption that merely names functions goes stale the moment one of
    them starts working, and the surface silently stops being measured.
    Asserting that each still raises turns the exemption red on the day
    the next phase implements it, which is the only way the isolation
    ends by construction rather than by someone remembering.
    """
    for name in UNIMPLEMENTED_STUBS:
        value = getattr(itacart, name)
        with pytest.raises(NotImplementedError):
            if isinstance(value, type):
                value()
            else:
                _call_with_anything(value)


def _call_with_anything(function: Callable[..., Any]) -> Any:
    """Call a stub with plausible arguments, since only the raise matters."""
    parameters = list(inspect.signature(function).parameters.values())
    required = [
        parameter
        for parameter in parameters
        if parameter.default is EMPTY
        and parameter.kind
        in (parameter.POSITIONAL_ONLY, parameter.POSITIONAL_OR_KEYWORD)
    ]
    return function(*(["NE(0001/0000)"] * len(required)))


def test_the_extra_argument_table_covers_every_consumer_that_needs_one() -> None:
    """A consumer that grows a required argument fails here, not silently."""
    needing = {
        name for name in _consumers() if _required_extras(getattr(itacart, name))
    }
    assert needing == set(EXTRA_ARGUMENTS), (
        f"missing from the table: {sorted(needing - set(EXTRA_ARGUMENTS))}; "
        f"stale in the table: {sorted(set(EXTRA_ARGUMENTS) - needing)}"
    )


# --------------------------------------------------------------------------
# The corpus, produced rather than written
# --------------------------------------------------------------------------


def _square(lon: float, lat: float, side: float) -> Polygon:
    return Polygon(
        [
            (lon, lat),
            (lon + side, lat),
            (lon + side, lat + side),
            (lon, lat + side),
        ]
    )


def _flatten(groups: Any) -> list[str]:
    out: list[str] = []
    for group in groups:
        out.extend(group if isinstance(group, list) else [group])
    return out


def _sample(cells: list[str], keep: int = 3) -> list[str]:
    """First, last and middle, so the sample is deterministic and small."""
    if len(cells) <= keep:
        return list(cells)
    return [cells[0], cells[len(cells) // 2], cells[-1]]


def _build_corpus() -> dict[str, list[str]]:
    """Every entry is here because something broke on it."""
    corpus: dict[str, list[str]] = {}

    # A cell set spanning two quadrants, which compose writes and the
    # serializer once refused.
    crossing = ["NE(0001/0001)", "NE(0002/0001)", "NW(0003/0004)"]
    corpus["compose over several quadrants"] = [itacart.compose(crossing)]

    # Regions over each boundary the fill has to survive.
    for label, polygon in (
        ("polyfill over the equator", _square(10.0, -0.02, 0.04)),
        ("polyfill over the meridian", _square(-0.02, 10.0, 0.04)),
        ("polyfill over the origin", _square(-0.02, -0.02, 0.04)),
        ("polyfill in the interior", _square(10.0, 10.0, 0.04)),
    ):
        index = itacart.polyfill(polygon, 4, compact=False)
        corpus[label] = [index, *_sample(itacart.decompose(index))]

    # An extension zone: ground the fill once refused entirely.
    west, south, _, _ = itacart.extension_bounds("CHUKOTKA")
    zone = _square(west + 0.01, south + 0.01, 0.04)
    zone_index = itacart.polyfill(zone, 4, compact=False)
    corpus["polyfill inside an extension zone"] = [
        zone_index,
        *_sample(itacart.decompose(zone_index)),
    ]

    # A compacted fill, whose meaning changed after this codec was written.
    compacted = itacart.polyfill(_square(10.0, 10.0, 0.04), 4, compact=True)
    corpus["polyfill compacted"] = [compacted, *_sample(itacart.decompose(compacted))]

    # Row zero, on both sides of the equator.
    corpus["row zero across the equator"] = [
        itacart.compose(["NE(0625/0000)", "SE(0625/0000)"]),
        "NE(0625/0000)",
        "SE(0625/0000)",
    ]

    # Column zero: the meridian triangle, which exists only in the east.
    corpus["the meridian triangle"] = [
        itacart.compose(["NE(0000/0451)", "SE(0000/0451)"]),
        "NE(0000/0451)",
    ]

    # The trapezoid's surplus child, which lands one column past the last
    # column that is a cell.
    trapezoid = "NE(2003/0000)"
    corpus["the trapezoid's children"] = [
        itacart.compose(_flatten(itacart.get_children(trapezoid))),
        "NE(2004/0000(3))",
        trapezoid,
    ]

    # The polar row, whose parent yields more children than the ratio.
    polar = "NE(0001/0999)"
    corpus["the polar row"] = [
        itacart.compose(_flatten(itacart.get_children(polar))),
        polar,
    ]

    return corpus


CORPUS = _build_corpus()


def test_every_corpus_entry_is_populated() -> None:
    """Declare the size of every entry, so a green table cannot hide a zero.

    A bucket that silently emptied is the failure mode this guards: the
    table stays green while measuring nothing.
    """
    sizes = {label: len(entries) for label, entries in CORPUS.items()}
    assert len(sizes) == 11, f"expected eleven entries, got {sorted(sizes)}"
    assert all(count > 0 for count in sizes.values()), sizes
    assert sizes == {
        "compose over several quadrants": 1,
        "polyfill over the equator": 4,
        "polyfill over the meridian": 4,
        "polyfill over the origin": 4,
        "polyfill in the interior": 4,
        "polyfill inside an extension zone": 4,
        "polyfill compacted": 4,
        "row zero across the equator": 3,
        "the meridian triangle": 2,
        "the trapezoid's children": 3,
        "the polar row": 2,
    }


def test_the_corpus_reaches_the_families_it_names() -> None:
    """Each entry contains what its name claims, not merely something."""
    equator = CORPUS["polyfill over the equator"][0]
    assert sorted({cell[:2] for cell in itacart.decompose(equator)}) == ["NE", "SE"]

    meridian = CORPUS["polyfill over the meridian"][0]
    assert sorted({cell[:2] for cell in itacart.decompose(meridian)}) == ["NE", "NW"]

    zone = CORPUS["polyfill inside an extension zone"][0]
    cells = itacart.decompose(zone)
    assert all(itacart.is_extension_cell(cell) for cell in cells)

    assert any(
        entry.startswith("NE(2004/") for entry in CORPUS["the trapezoid's children"]
    )
    assert itacart.is_trapezoidal_cell("NE(0001/0999)")


# --------------------------------------------------------------------------
# The predicate
# --------------------------------------------------------------------------


def _call(name: str, argument: str) -> None:
    """Call one consumer with one produced index.

    Answering and refusing are both acceptable. Many refusals are correct:
    there is no cell above the quadrants, a lattice distance is undefined
    across a trapezoid, and a compositional index is not a single cell.
    What is never acceptable is an exception from outside the package's
    own hierarchy, because that is a fault escaping rather than a rule
    being applied.
    """
    function = getattr(itacart, name)
    first = _first_parameter(function)
    value: Any = [argument] if first == "cells" else argument
    function(value, *EXTRA_ARGUMENTS.get(name, ()))


#: Escapes this instrument found and this phase may not repair, because the
#: defect is in the core and the core is another phase's to touch. Pinned by
#: number rather than marked expected: a bare count says how much is wrong,
#: where an expectation marker only says that something is, and lets a
#: worsening go on passing.
#:
#: ``cells_to_directed_edge`` refuses a cardinality mismatch with a bare
#: ``ValueError``. Its two siblings over the same argument shape,
#: ``are_neighbor_cells`` and ``grid_distance``, refuse the identical
#: situation with ``NonAtomicIndexError``. The docstring declares the
#: ``ValueError``, so it was written deliberately; that makes it a rule to
#: revisit rather than an oversight to patch here.
KNOWN_ESCAPES: dict[tuple[str, str], int] = {
    ("cells_to_directed_edge", "ValueError"): 11,
}


def _escapes_over(labels: list[str]) -> tuple[dict[tuple[str, str], int], list[str]]:
    counts: dict[tuple[str, str], int] = {}
    detail: list[str] = []
    for label in labels:
        for name in _consumers():
            for entry in CORPUS[label]:
                try:
                    _call(name, entry)
                except ITACaRTError:
                    continue
                except NotImplementedError:
                    key = (name, "NotImplementedError")
                except Exception as exc:  # noqa: BLE001 - the point of the test
                    key = (name, type(exc).__name__)
                else:
                    continue
                counts[key] = counts.get(key, 0) + 1
                detail.append(f"{label}: {name}({entry!r}) -> {key[1]}")
    return counts, detail


@pytest.mark.slow
def test_the_surface_accepts_what_the_package_produces() -> None:
    """No produced index makes a consumer raise outside the hierarchy.

    The one predicate that would have caught the multi-quadrant defect.
    Answering and refusing are both acceptable; refusing with an exception
    the package does not own is not, because that is a fault escaping
    rather than a rule being applied.

    Pinned by number. A new escape fails here, and so does repairing a
    known one, which forces the pin down rather than letting it rot.
    """
    counts, detail = _escapes_over(sorted(CORPUS))
    assert counts == KNOWN_ESCAPES, "\n".join(detail)


def test_the_predicate_would_have_caught_the_multi_quadrant_defect() -> None:
    """The instrument is tested against the defect that motivated it.

    A predicate nobody has seen fail is a predicate nobody knows measures
    anything. Feeding a consumer a spelling it genuinely refuses shows the
    machinery reporting rather than passing by default.
    """
    from itacart.exceptions import InvalidIndexError

    with pytest.raises(InvalidIndexError):
        itacart.encode_tree("NW(0000/0451)")

    escapes: list[str] = []
    try:
        itacart.encode_tree("NW(0000/0451)")
    except ITACaRTError:
        pass
    except Exception as exc:  # noqa: BLE001 - mirrors the predicate above
        escapes.append(str(exc))
    assert escapes == []
